//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class ProjektDBEntities4 : DbContext
{
    public ProjektDBEntities4()
        : base("name=ProjektDBEntities4")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<Kategori> Kategoris { get; set; }
    public virtual DbSet<Perdoruesit> Perdoruesits { get; set; }
    public virtual DbSet<Porosite> Porosites { get; set; }
    public virtual DbSet<Produkte> Produktes { get; set; }
}
